info:
  contact: {}
  description: 用Go实践
  title: 学习项目
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: 标签名称
        in: query
        maxLength: 100
        name: name
        type: string
      produces:
      - application/json
      responses: {}
      summary: 获取多个标签
swagger: "2.0"
